name: 03 Build and Publish to GCP Artifact Repository

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/03-build-deploy-app.yml"
      - "src/**"

env:
  GCP_DOCKER_HOST: ${{ vars.GCP_REGION_NAME }}-docker.pkg.dev
  WEB_CONTAINER_IMAGE: ${{ vars.GCP_REGION_NAME }}-docker.pkg.dev/${{ vars.GCP_ARTIFACTS_PROJECT_ID }}/${{ vars.GCP_ARTIFACTS_REPOSITORY_ID }}/${{ vars.WEB_CONTAINER_IMAGE_NAME }}
  WEB_CONTAINER_PORT: ${{ vars.WEB_CONTAINER_PORT }}

jobs:
  Build_and_Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Short SHA
        run: echo "GH_SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      - name: Authorise with GCloud
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_DEPLOY_CREDENTIALS }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Credential Helper
        run: |-
          gcloud auth configure-docker ${{ env.GCP_DOCKER_HOST }}

      - name: Login to Google Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.GCP_DOCKER_HOST }}
          username: _json_key
          password: ${{ secrets.GCP_SERVICE_ACCOUNT_DEPLOY_CREDENTIALS }}

      - name: Build and Push to Google Artifact Registry
        uses: docker/build-push-action@v2
        with:
          context: ./src
          push: true
          tags: |
            ${{ env.WEB_CONTAINER_IMAGE }}:latest
            ${{ env.WEB_CONTAINER_IMAGE }}:${{ env.GH_SHORT_SHA }}

      - name: Update GitHub Repository Variables with Container Image Path and Port
        env:
          GITHUB_TOKEN: ${{ secrets.GH_REPOSITORY_PAT }}
        run: >-
          gh api
          --method PATCH
          -H "Accept: application/vnd.github+json"
          repos/${{ github.repository }}/actions/variables/WEB_CONTAINER_IMAGE
          -f value='${{ env.WEB_CONTAINER_IMAGE }}:latest'

          gh api
          --method PATCH
          -H "Accept: application/vnd.github+json"
          repos/${{ github.repository }}/actions/variables/WEB_CONTAINER_PORT
          -f value=${{ env.WEB_CONTAINER_PORT }}

      # Call Infra workflow to update image in Cloud Run.
      - name: Call IaC Workflow
        run: >-
          RESPONSE_CODE=$(curl
          -s
          -o /dev/null
          -w "%{http_code}"
          -X POST
          -H "Accept: application/vnd.github+json"
          -H "Authorization: Bearer ${{ secrets.GH_REPOSITORY_PAT }}"
          -H "X-GitHub-Api-Version: 2022-11-28"
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/02-iac-provision-app-resources.yml/dispatches
          -d '{ "ref":"main", "inputs": {} }')

          if test $RESPONSE_CODE -ne 204; then
            echo "Response: $RESPONSE_CODE"
            exit 1
          fi
